### ISSUE TITLE
Is there a way to track damage that is absorbed?

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#102]
I'm struggling to find a way to track damage that is absorbed by abilities like Oracle's False Promise. I thought there would be a separate entity that is created upon using the ability and then all damage goes through that instead of the original target, but I wasn't able to find anything. I've tried the combat log, but the damage doesn't show up until the buff expires, and I'd like to be able to see the moment when damage is dealt to the target, and not afterwards.

Does anyone know how the replays keep track of the moment damage is absorbed and by who the damage is done, and how I can access this information? Thanks!

**Comment by spheenik** [comment]
Very good question. I do not have a clue. 

But if you want me to follow my gut, I'd say forget it, since there's no incentive (or need) to put that value out. From the server's perspective, it's perfectly fine to keep the sum for itself until it speaks it's verdict at the time the combat log comes out as well. 

Is there visual indication of something hitting the hero with false promise? If so, you can detect that via particle effects. Then you'd have the number of instances something hit. But then....

**Comment by TodorovicF** [comment]
Hmm I was afraid of that, but it makes sense I guess. I can take a look at particles but it seems that it would be too unreliable. Thanks a lot for the insight anyway!
