### ISSUE TITLE
Ability to track when items/abilities percentage-based triggers occur

### ISSUE THREAD

**Issue by TodorovicF** [skadistats/clarity#103]
I've looked through the CombatLog and Ability/Item Entities and I can't seem to find any way to catch when a passive ability or item triggers, like a % to do extra damage. Is there any way to do this reliably or only by looking at all damage and calculating the differences? Thanks!

**Comment by spheenik** [comment]
I wish I could help, but the only thing I can add is that this also smells like it might be impossible because of the general "server computes and gives you the result without needing to explain further".

You might have some luck here and there though, depending on the ability in question. For example when the special is accompanied by a particle effect.

**Comment by TodorovicF** [comment]
Thanks for the reply! I understand, this is pretty much what I expected, but good to know that I didn't miss something :)

**Comment by spheenik** [comment]
Sure, but we might *both* have missed something. :)
