### ISSUE TITLE
Camps Stacking

### ISSUE THREAD

**Issue by Dmytro4** [skadistats/clarity#110]
Is there any way to detect when and which neutral camp was attacked and who actually did this? 
So if there is no simple way i need to detect somehow that creeps was pulled (how i can detect that creeps was provoked by hero or his creeps? I can detect damage dealt but i can pull just by running near to creeps without any damage) and that new creeps was spawned on same place.

How can i detect neutral camps? Is there any indexes on every camp or every creep? Or i just need to detect camps by coordinates?
Please help!

**Comment by spheenik** [comment]
While not knowing for sure, I think there must be some entities in the game that describe neutral camps, since you can show their extent with yellow lines while playing.

I suggest using [clarity analyzer](https://github.com/spheenik/clarity-analyzer) for browsing the entity data.

**Comment by TodorovicF** [comment]
There is a property called `m_vecDataTeam.000[player-slot].m_iCampsStacked` within the `CDOTA_DataRadiant` and `CDOTA_DataDire` entities (where player-slot is 0-4 corresponding to their position in the roster), but I'm not sure how accurate, if at all, this property is. I remember testing it months ago and it didn't hold correct data, so I had to implement something myself, though it might work correctly now with recent updates so I'd give it a try.

What I basically did otherwise was get every neutral creep on the map at about 1 second after their spawn times (just to be sure they're all spawned) and store them with a unique id (the easiest thing to use is their Entity's index via `getIndex()` as this will always be unique to every Entity that is currently "alive", once they're dead this ID may be recycled but it's usually not reused for some time). Camps and Neutral Creeps both use the same name for all of their Entities, so you can get an Iterator for all Neutrals using `Context.getProcessor(Entities.class).getAllByDtName("CDOTA_BaseNPC_Creep_Neutral")` and one for all Camps using `Context.getProcessor(Entities.class).getAllByDtName("CDOTA_NeutralSpawner")`. With these, you can get their locations and tie each Neutral entity to the camp it's currently at.

Once you've mapped each Neutral to their camp and stored each Neutral's ID, you'll wait for the next spawn time, get all of the new Indexes, and if there are any IDs in the new list of Neutrals that were in the old list that you stored, then that the camp was stacked, otherwise remove IDs that don't match any of the new Neutrals as they have been killed.

You can go further and mark which Neutrals were part of which group, perhaps by using their spawn time as a second ID, and see how many unique timestamps there are in your list. This way, you can get how many times a camp was stacked, as well as the highest number of stacks each camp had. The tricky thing here is identifying which Hero initiated the stacking, and honestly I haven't found an accurate way, other than using the combat log to see who was the last person to attack a Neutral at a specific camp before it was stacked. Hope this helps!

**Comment by spheenik** [comment]
Thanks a lot for helping out @TodorovicF, much appreciated!

**Comment by TodorovicF** [comment]
No problem, it's the least I can do :)
