### ISSUE TITLE
Any manuals?

### ISSUE THREAD

**Issue by zhshr** [skadistats/clarity#12]
Sorry for bothering. I'm using the library for parsing replays but I found it a little difficult to use. I read the example of combatLog throughly but I still can't figure out how to get other messages at the same time. Is there any way to get similar to this library?

**Comment by shtefcs** [comment]
Anyone of you guys created something cool from Clarity ? @eimyss @zhshr @ChrisE87 @spheenik @PatheticNeatness @sebyx07 . 

I am looking to use Clarity for Dota 2 app and I need developer. If anyone interested, hit me up on skype:ksifoking or email:shtefistefi@yahoo.co.uk

**Comment by ChrisE87** [comment]
I didn't do it in the end unfortunately and now I'm simply lacking time :/. 

However, I wrote a program for my master's thesis which worked with most of the basic data. My goal was to classify play styles with Machine Learning, so I sometimes accepted little accuracy issues as long as the tendency of their play style was still recognizable. Looked like this: http://abload.de/img/playerclassifierqayq1.png

This includes:
- Everything you see at the end of a match: Most things are covered by a basic example from spheenik, but I think at least items were not present. 
- Estimations of the position (Top, Bot, Mid, Jungle Top, Jungle Bot, Roaming) - very accurate in my test data, should be almost 99% unless position shifts are happening. 
- Estimations of Team Fights (time and participants): Some situations where it doesn't work due to some restrictions, but overall it worked better than I expected. 
- Estimations of Early Ganks (up to 10 game-minutes): Many false positives for Roamers (for whom every attack is considered a Gank), but worked pretty well for me to filter out very aggressive/active players
- Utiziling this and other stuff to estimate 9 play styles using the WEKA library. Accuracy only is at about 75% though. I also did a basic role differentiation according to another work (Carry, Support, Solo Lane) which was at about 96%. 

So I worked much with positioning, combat logs and general info and also combined those for further estimations. If there are any questions or if you want more information (my messy code, algorithm descriptions...) regarding that, you can drop an E-Mail to eggert.christoph<-YouKnowTheSign->gmail.com .

I'm pretty busy now though, so answers might take a while as I probably have to look up how I did some things :D. I also can't join any projects as a developer for that reason.

**Comment by PatheticNeatness** [comment]
@shtefcs I was built app that shows replays end stat for local purposes :D with clarity + examples it was very easy :D

**Comment by shtefcs** [comment]
@PatheticNeatness Can you show me ^^ ? if you can add me on skype or email above

**Comment by PatheticNeatness** [comment]
np, but be ready to shitcode and hacks :D 
my app just parse replays to save endstats on mongodb, nothing serious :). So you can contact with email patheticneatness@gmail.com

**Comment by spheenik** [comment]
Y'all realize this isn't exactly the thread for this? :oncoming_police_car: 
Btw: Chris, nice screenshot!

And a little publicity: 2.0 is in beta. Please all check it out. Spent the last week optimizing, for what was the entity profile in 1.0 it is now twice(!) as fast! :checkered_flag:

**Comment by shtefcs** [comment]
@spheenik sorry man, I knew it u gonna say it. This was the best and fastest way to get right guys contacted.

**Comment by spheenik** [comment]
@shtefcs

sure, no problem. Is it possible to elaborate a little on what you want, or do we need to sign an NDA first? :mask: :smile:

**Comment by shtefcs** [comment]
hehe, no need for NDA ^^, but i would like to share my idea on private. You can get me on skype:ksifoking or email:shtefistefi@yahoo.co.uk
