### ISSUE TITLE
How to understand which ability killed?

### ISSUE THREAD

**Issue by inShu** [skadistats/clarity#132]
Hi,
There is no chance to get ability handle which killed someone as far as I can understand? No information in life state changes or combatlog. Dying or Dead life state doesn't matter. I tried to log begin and end of ability casting but delay in hero death announcing through messages could be equal up to 0.3 second. So I have such picture:
[1.0 s] hook casted
[1.4 s] hook casting done
[1.7 s] hero killed
This is example when Pudge killing someone with hook. My idea was to catch hero death between hook begin/end steps. It also impossible to get hook modifier on victim when Pudge killing him with that hook: damage applied first and no hook modifier applied.

Maybe you have ideas?
Thank you.

**Comment by TodorovicF** [comment]
Do you have a sample of your code and how you're getting this data? If you listen for `CombatLog `entries using `@CombatLogEntry`, then you can look for `DOTA_COMBATLOG_DEATH` specifically or `DOTA_COMBATLOG_ABILITY`, and then the `CombatLogEntry` object will contain a method `getInflictorName()` which returns the name of whatever killed the hero, in this case it would be Pudge's Hook. The name will be something like `pudge_hook` or `modifier_pudge_hook`. You can probably use the ComatLog along with your current code to tie the two together and get accurate event times.

So something like this:
```
@OnCombatLogEntry
public void onCombatLog(Context ctx, CombatLogEntry cle) throws UnsupportedEncodingException {
    if (cle.getType().equals(DOTA_COMBATLOG_TYPES.DOTA_COMBATLOG_DEATH)) {
        Entity proxy = ctx.getProcessor(Entities.class).getByDtName("CDOTAGamerulesProxy");
        float time   = (Float)proxy.getProperty("m_pGameRules.m_fGameTime") - timeBeforeGame;
        String abilityName  = cle.getInflictorName();
        String attackerName = cle.getAttackerName();
        String targetName   = cle.getTargetName();
       
        System.out.println(attackerName + " killed " + targetName + " with " + abilityName + " at : " + time);
    }
}
```

`timeBeforeGame` is the time right up until the first Hero spawns and the game time starts. This is needed because the time given by `CDOTAGamerulesProxy`'s `m_fGameTime` includes the ban/pick phase, so it's not very useful for accurately linking events during the game. The best way I know to get the `timeBeforeGame` is to listen for a PropertyChange in `CDOTAGamerulesProxy` and grabbing the property `m_pGameRules.m_flGameStartTime` when it's no longer 0. Then simply subtract the time from the current Context by this, as I did in the example above, and you'll get the exact in-game time.

Also, the CombatLog contains events such as `DOTA_COMBATLOG_MODIFIER_ADD` and `DOTA_COMBATLOG_MODIFIER_REMOVE` if you want to get Pudge's hook modifier as well. The modifier name will also come from the `getInflictorName()` method. Hope this helps!

**Comment by inShu** [comment]
I will check this out! Thank you!
