### ISSUE TITLE
@OnEntityPropertyChanged fires before @OnEntityCreated

### ISSUE THREAD

**Issue by inShu** [skadistats/clarity#134]
Hi,
Today I caught a very strange behavior of clarity 2.2.
```
@OnEntityPropertyChanged(classPattern = "CDOTA_Unit_Hero_.*", propertyPattern = "m_iTaggedAsVisibleByTeam")

@OnEntityCreated

```
First event can fire before second one. Most magical thing here is that this trouble occurs only if you try to debug your application. Also this is a floating problem and appears periodically.
Did anyone faced such bug?

**Comment by spheenik** [comment]
This occurs because `@OnEntityPropertyChanged` is built upon `@OnEntityCreated`.

Basically, clarity holds (Hash-)Sets of entity listeners. Whenever an event is raised, all listeners are called once in an undefined order. 

I agree something should be done about this. But I have not made up my mind about how.

I think the best way to do it is to add some kind of `@CallOrder` annotation on the listener, where my handler of `@OnEntityCreated` can specify that it always wants to be called after yours.

**Comment by inShu** [comment]
I think that first of all you should have hardcoded order in clarity by itself. First you got to call all @OnEntityCreated and after that all others according to logic. And that mechanics should be changeable
from outside with something like @CallOrder which you mentioned.

**Comment by spheenik** [comment]
Well it kind of IS hardcoded to be undefined. 
In this particular case, we want to call mine last. But you could construct cases where you want it the other way around. So how should I hardcore it in clarity?
