### ISSUE TITLE
Match identifier is 0

### ISSUE THREAD

**Issue by inShu** [skadistats/clarity#140]
Hi,
Match - https://www.dotabuff.com/matches/3084135978
Replay - http://replay193.valve.net/570/3084135978_1889616632.dem.bz2
`CDotaGameInfo info = Clarity.infoForFile(filePath).getGameInfo().getDota();`

**info.getMatchId()** returns **0**

**Comment by inShu** [comment]
Guys, I'm sorry, but are you serious? How we can use your API if you are not eventually saying anything about bug reports? I'm building web-service based on your API and I'm terrified what to expect when new version of Dota will came out. I will need to stop it for months?

**Comment by spheenik** [comment]
Yea, that makes me wanna answer even more quickly.
I don't remember you employing me. So this project is a project I do in my free time.
I don't have that atm.

So I suggest you go use something else!

**Comment by spheenik** [comment]
And regarding your "bug". I do not think this is a bug in Clarity. So maybe find another way to get your match id. 

I fucking hate your tone, mister. Please, go use Manta and ANNOY THEM. Thank you.

**Comment by inShu** [comment]
Ok. Will do. Just for your information: mark your project as "Almost not supported, so go fuck yourselfs". That will make people understand your point of view quickly and you can avoid such topics.

Good luck.

**Comment by spheenik** [comment]
Well, I still support this project, just not when folks like you come around and suppose they are **entitled** to something. And for small, minor cases like yours, your bug report indicates that you didn't give a shit researching yourself, since you only dumped your request, without any word about what research you did before posting.

But then again, even that is not the problem. The problem is 

> Guys, I'm sorry, but are you serious?

Who do you think you are? Who do you think I am in relation to you? 

Somehow the guys at opendota, stratz and several other places just somehow manage to ask their questions in a way that doesn't trigger me.
