### ISSUE TITLE
Detect items being sold

### ISSUE THREAD

**Issue by frozenspider** [skadistats/clarity#144]
If I get it right, event `DOTA_COMBATLOG_GOLD` with `getGoldReason() == 6` corresponds to an item being sold. However, I currently see no way of seeing which item was sold. Is this information available in the event stream? If no, how can I deduce it? (Since we can see this in Dota game, this must be deducible in some way)

**Comment by spheenik** [comment]
I don't know, so only general guidelines: If it is not deducible via combat log, you'll certainly see it in the entities. 

Every hero entity has entity handles for every inventory slot. So if you keep track of it this way, you will be able to detect when an item has been removed from the inventory. 

Since it might also have been dropped (not sold), it might be needed to do some correlation between the two. 

I recommend clarity-analyzer for looking at the entity data.

**Comment by STRATZ-Ken** [comment]
To lead you in the correct direction, don't use the CombatLogs.  Use onSpectatorPlayerUnitOrders and

`if (message.getOrderType() == 16 || message.getOrderType() == 17)`
