### ISSUE TITLE
ControllableRunner#getContext return null

### ISSUE THREAD

**Issue by dierke9** [skadistats/clarity#154]
Currently trying to recreate the end of game scoreboard.
When doing the ControllableRunnner.getContext() method this return null reulting in an exception to get the Entities Processor.

Code:
`
runner = new ControllableRunner(new MappedFileSource(file));
runner.setDemandedTick(runner.getLastTick());
Entity playerResource = runner.getContext().getProcessor(Entities.class).getByDtName("CDOTA_PlayerResource");
`

**Comment by spheenik** [comment]
You did not supply a processor that uses entities, that's why it is not there.

See [the matchend example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/matchend/Main.java#L34-L36) on how to properly do this.

Notice the `runWith(this)`, and this being annotated with `@UseEntities`.

**Comment by dierke9** [comment]
Yes that seems to fix my problem. Thanks you :)
