### ISSUE TITLE
Is it possible to check each hero in-game role/lane from the .dem replay file?

### ISSUE THREAD

**Issue by pFnX** [skadistats/clarity#166]
As the title states, I need to be able to extract which was the role (carry/mid/offlane/roam/support) of each hero from the .dem file. I used the clarity analyzer and look through various classes but none of them has the property of in-game role. 
If the roles aren't possible, I would be happy with the lane each hero went. For example in opendota website, when you chose a replay and you click the "Laning" section, you are able to see what lane each hero went, just like this:

![laning](https://user-images.githubusercontent.com/17179374/37987189-69d0c4cc-31f5-11e8-8945-77cc0cb7a018.JPG)

Is it possible to extract at least the laning info of each hero with clarity? If not, does anyone know how can I have access to this opendota info about laning to have it saved in a text file? 

Thanks in advance!

**Comment by howardchung** [comment]
Clarity allows you to extract the raw position data.

OpenDota attempts to categorize this position data into a lane using a rule-based approach by bucketing the map into sections:
https://github.com/odota/core/blob/master/util/utility.js#L688

You can also fetch the data from the OpenDota API:
https://api.opendota.com/api/matches/3641054086

(see the lane and lane_role properties)

**Comment by ChrisE87** [comment]
Regarding lanes (haven't looked into this topic for quite a while, so howardchungs's examples might be better by a margin): 
I have written a tool back in 2015 which also tried to figure out which lane each hero was playing (including "roaming" if there didn't seem to be a specific lane). I spent a lot of time fine-tuning this with manual adjustments, so I was pretty confident in its predictions. Since it was in 2015, I am not sure how useful it is anymore though. Clarity worked very different and the replay files probably changed as well. If you have some example replay file, I could just try to put it into that tool and see if it still spits out good results, and if it is of use, I could provide the source code.  
  
Regarding roles:  
This is actually an incredibly hard topic if you want to avoid making assumptions based on heroes or something similar (even with that). I based my master thesis on this and had a paper published out of it (https://www.researchgate.net/publication/289526483_Classification_of_Player_Roles_in_the_Team-Based_Multi-player_Game_Dota_2), ending up with ~75% accuracy for very specific roles, and roughly 96% with 3 basic roles. There's tons of reasons that can end this up being incredibly inaccurate. Most importantly a very loose definition of roles, and playstyles that tend to dance around the border of two. I actually let some players classify "roles" in a tournament game to see if humans agree with that, and noone was rating the players 100% the same. If even experts disagree regarding this, the algorithm will have a hard time doing the same. Additionally, the actual indicators are also influenced e.g. by you being on the winning or losing end. So things like gold per minute etc. can end up being not too helpful if your team is simply getting stomped. 

To be fair, a lot has happened in the meantime (apparently the game itself summarizes teamfights for example, I had to try this on my own), so there's probably a lot of potential for better results. 

Can try and see if the tool still works with modern replays, kinda have my doubts though seeing the issues coming up here over time :D.

**Comment by pFnX** [comment]
Thank you very much for the fast replies. 
I've decided to take the fecthing data approach, from the Opendota API, since my program receives the dem file ID as input it was easy for me to capture this particular info that opendota provides, and this thankfully solved my problem. I will also take a closer reading at ChrisE87's paper when i have the chance, since just by looking at it for a few mins, I found that you also address the labeling of replays which is something I'm interested in.

Thanks again for your time explaining this to me, I'm just a beginner but eagering to learn! :D
