### ISSUE TITLE
no compatibility with JDK9 and above

### ISSUE THREAD

**Issue by FloydBull** [skadistats/clarity#175]
I am trying to package the project and I am getting this error below. Sorry, this might be an easy fix. Yet, I can find an answer. Thanks in advance. 

Exit code: 1 - C:\Users\gislabasst\git\clarity\src\main\java\skadistats\clarity\source\LiveSource.java:12: error: package sun.nio.ch is not visible
[ERROR] import sun.nio.ch.DirectBuffer;
[ERROR]               ^
[ERROR]   (package sun.nio.ch is declared in module java.base, which does not export it to the unnamed module)
[ERROR] C:\Users\gislabasst\git\clarity\src\main\java\skadistats\clarity\source\MappedFileSource.java:3: error: package sun.nio.ch is not visible
[ERROR] sun.nio.ch.DirectBuffer;
[ERROR]        ^
[ERROR]   (package sun.nio.ch is declared in module java.base, which does not export it to the unnamed module)
[ERROR]
[ERROR] Command line was: "C:\Program Files\Java\jdk-10.0.1\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\gislabasst\git\clarity\target\apidocs' dir.

**Comment by spheenik** [comment]
Clarity does not work with JDK 9 and above, since I use private JDK classes. I made some attempts to fix this in the past, but the results sucked.
So right now, the easiest fix is to use JDK8.

**Comment by spheenik** [comment]
Add double quotes around the filename!

**Comment by kivimango** [comment]
Hello ! I have this problem too, cannot build on Java 11 because of the following errors:

Error:java: the unnamed module reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module protobuf.java reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module snappy.java reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module slf4j.api reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module cloning reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module objenesis reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module classindex reads package com.google.protobuf from both clarity.protobuf and protobuf.java
Error:java: module clarity.protobuf reads package com.google.protobuf from both protobuf.java and clarity.protobuf
Error:java: module clarity reads package com.google.protobuf from both clarity.protobuf and protobuf.java

**Comment by spheenik** [comment]
I know, and I am sorry, but I only support JDK 8 at the moment, because I do some nasty stuff to get performance to where I want it to be... I have made several attempts to fixing this, but abandoned them all because they sucked. So I advise you to use JDK 8!

**Comment by spheenik** [comment]
Fixed with today's release of 2.7.0
