### ISSUE TITLE
Is it possible to run this as a sub process in Node?

### ISSUE THREAD

**Issue by LiamDotPro** [skadistats/clarity#188]
I'm looking to see if I can run the parser alongside a copy of node, how possible would it be?

**Comment by spheenik** [comment]
Never done it. Quick look in the documentation reveals that you can certainly spawn java as a node subprocess, but I wonder how you would communicate. Since clarity uses event handlers (in Java code), the only way I see this implemented with not much work is to build a Java app that dumps all you want to know to stdout. Is that feasible?

**Comment by LiamDotPro** [comment]
I guess I was under the impression that I might be able to talk to clarity using the stdIn provided on the sub process when spawning the java app, but I haven't actually really tested this at all. Are there other options where I can some how spawn clarity on a web server or something and then provide an API so other clients can gather data to be used?
