### ISSUE TITLE
CDotaGameInfo.getMatchId() returns 0

### ISSUE THREAD

**Issue by omorgan7** [skadistats/clarity#244]
Hello,

A very strange bug has occurred, I'm using code that looks approximately like this:

```java
CDemoFileInfo info = Clarity.infoForFile(args[0]);

        HashMap<String, Object> outInfo = new HashMap<>();
        CGameInfo gameInfo = info.getGameInfo();
        CDotaGameInfo dota = gameInfo.getDota();

        System.out.println(dota.getMatchId());
```

The exact code i'm using can be found [here](https://github.com/omorgan7/mjollnir/blob/master/src/main/java/mjollnir/Main.java#L52).

Strangely, for this particular replay I'm getting a match ID returned of 0. Everything else seems to parse ok. My java version my server is the following:

```
# java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

The match ID should have been 5697202414.

Here is a link to the file: https://gofile.io/d/cfI1Ka

**Comment by spheenik** [comment]
Are you saying that you have been using this code for a while and it would normally yield the correct match id?
If so, then something abnormal has to have happened on Valve's side, because the match id is simply not encoded in the info.

I checked the replay, the match ID is still available in the `CDOTAGamerulesProxy` entity at `m_pGameRules.m_unMatchID64`.

**Comment by omorgan7** [comment]
Interesting. Perhaps the download got corrupted from valve's servers? IDK. Anyway thanks for looking into this, if I get any more strange replays in the future I'll just use `m_pGameRules`.
