### ISSUE TITLE
Proper attribution / licensing for code ported to JavaScript

### ISSUE THREAD

**Issue by timkurvers** [skadistats/clarity#246]
Clarity and its analyzer have been absolutely invaluable during my exploration of the Dota 2 replay file format. Thanks so much for providing these as open source projects!

As an experiment I've been building [ReDota](https://timkurvers.github.io/redota), a way to revisit past Dota 2 matches directly in the web browser without any server involvement.

Unfortunately, automatic conversion of both Clarity and Dotabuff's Manta parser to WebAssembly proved difficult, so I ended up porting Manta to JavaScript manually. I can imagine Manta borrows a bunch of logic from Clarity and, in addition, some pieces of code in ReDota are directly ported from Clarity, notably [string tables](https://github.com/timkurvers/redota/blob/master/src/lib/parser/StringTable.js#L30) and [handles](https://github.com/timkurvers/redota/blob/master/src/lib/parser/model/handle.js). Both parsers are attributed on the ReDota homepage, its README and mentioned inline as comments wherever relevant (may have missed a few spots).

As Clarity is not licensed under MIT, are these current attributions sufficient?

**Comment by spheenik** [comment]
Hey, first of all, congrats on your parser and your project! I even had a look at your readBit() function, since Javascript is so bad at doing this fast. Your approach looks good!

You're right: Some logic in Manta comes from Clarity, easily found by the camel case style! :)

Lot's of knowledge regarding the Source 2 demo format were acquired in 2015 in a collaboration of invokr and me: At that time, he was tasked by Dotabuff  to write a working parser, while I wanted to make mine fit for Source 2.

invokr later build the fastest Source 2 parser available:

https://github.com/ButterflyStats/butterfly

and I remember him running it in emscripten.
Unfortunately, he passed away in 2018. Noxville still keeps Butterfly alive and uses it for datdota radio!

Regarding your question: 

Yes, the attributions are sufficient.

**Comment by timkurvers** [comment]
> Hey, first of all, congrats on your parser and your project! I even had a look at your readBit() function, since Javascript is so bad at doing this fast. Your approach looks good!

Thanks, appreciate it! Pretty pleased with how it performs so far, but likely some gains hidden in plain sight still 😄 

> 
> You're right: Some logic in Manta comes from Clarity, easily found by the camel case style! :)
> 
> Lot's of knowledge regarding the Source 2 demo format were acquired in 2015 in a collaboration of invokr and me: At that time, he was tasked by Dotabuff to write a working parser, while I wanted to make mine fit for Source 2.
> 
> invokr later build the fastest Source 2 parser available: https://github.com/ButterflyStats/butterfly
> 
> and I remember him running it in emscripten.
> Unfortunately, he passed away in 2018.

Oh no, that's terrible to hear. 😞 I do recall having seen his profile, but I must have missed the Butterfly project itself.

> Noxville still keeps Butterfly alive and uses it for datdota radio!

Lovely gesture! And thanks for the tip on datdota radio, completely unaware that existed. Had toyed with the idea of decoding the audio streams, but may want to reach out to datdota instead first.

> Regarding your question: Yes, the attributions are sufficient.

Excellent, thanks 👍

Any channels/places you would recommend where replay parsing gurus such as yourself hang out?

**Comment by spheenik** [comment]
Completely forgot about your question.
Hmm. I'm kind of a loner, so I don't really know where/if people are hanging out together.

**Comment by timkurvers** [comment]
No worries! The OpenDota Discord server seems to have quite some activity 👍
