### ISSUE TITLE
CDOTAUserMsg_SpectatorPlayerUnitOrders order_type and ability_id

### ISSUE THREAD

**Issue by ucontacti** [skadistats/clarity#256]
I want to divide CDOTAUserMsg_SpectatorPlayerUnitOrders messages into three different categories. Attack action, Move action and Spell cast action. I need to know what is the order_type meaning. I mean I get the int value but I don't know the corresponding action equivalent. 
My other question is I try to get the name of ability from ability_id that this message contains. But I do not get the ability name from entitynames string table. It is always null. I used this stringtable conversion before for items entity name conversion successfully. 
This is the piece of code that I use:
```
    public String getEntityNameByHandle(int id, Entities entities, StringTable stringTable) {
        Entity entity = entities.getByHandle(id);
        int index;
        if (entity == null) {
            return null;
        }
        else {
            index = entity.getProperty("m_pEntity.m_nameStringableIndex");
            return stringTable.getNameByIndex(index);
        }
    }

    @UsesStringTable("EntityNames")
    @UsesEntities
    @OnMessage(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void onMessage(Context ctx, DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders message) {
        Entity e = ctx.getProcessor(Entities.class).getByIndex(message.getEntindex());
        Entities entities = ctx.getProcessor(Entities.class);
        StringTable stringTable = ctx.getProcessor(StringTables.class).forName("EntityNames");
                
        if (message.hasAbilityId())
        {
        int ability_id = message.getAbilityId();
            String ability_name = getEntityNameByHandle(ability_id, entities, stringTable);
                log.info("ability name : {}", ability_name); //Always_null
        }
        // Divide message type into actions
        switch (message.getOrderType()) {
            case value:
                //Move action
            case value:
                //Spell action
            case value:
                //Attack action
        }
    }
```

**Comment by ucontacti** [comment]
Yes, I think it is, how about other question about ability name? You can see my code for reference.

**Comment by spheenik** [comment]
There is a string table `AbilityNames`. `ability_name` is most certainly a direct index into this string table.

**Comment by BusyLivingDota** [comment]
I'm recently trying to work on these DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders. I am not so sure(or should I say I dont think, but I really havn't started on StringTables yet) there is relation betweent the output and StringTables, but I believe the IDs mean the index of entities exactly what showed in Clarity Analyzer(the 1st colume of all entities).

I received a lot of NPE because sometime like target is a tree, so I have to pick those cases out manually.

here is my processor:

@UsesEntities
public class MyTest {
    @Insert
    Entities entities;

    //private final Logger log = LoggerFactory.getLogger(MyTest.class.getPackage().getClass());
    @OnMessage(DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class)
    public void onMessage(Context ctx, DotaUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders message) {
        System.out.println(message.toString());
        System.out.println("entiindex: " + ctx.getProcessor(Entities.class).getByIndex(message.getEntindex()).getDtClass().getDtName());
        System.out.println("order_type: " + DotaCommonMessages.dotaunitorder_t.valueOf(message.getOrderType()));
        if (message.getUnitsCount() != 0) {
            System.out.println("Unit: " + entities.getByIndex(message.getUnits(0)).getDtClass().getDtName());
        }
        if (message.hasTargetIndex()) {
            if (message.getOrderType() != 7 && message.getOrderType() != 14 && message.getOrderType() != 15
                    && message.getOrderType() != 16 && message.getOrderType() != 19) {
                System.out.println("target: " + entities.getByIndex(message.getTargetIndex()).getDtClass().getDtName());
            }
        }
        if (message.hasAbilityId()) {
            if (message.getOrderType() != 16 && message.getOrderType() != 19) {
                System.out.println("ability_id: " + entities.getByIndex(message.getAbilityId()).getDtClass().getDtName());
            }
        }
        System.out.println(ClockTime.getClockTime(entities));
        System.out.println("============================");
    }

    public void run(String[] args) throws Exception {
        long tStart = System.currentTimeMillis();
        new SimpleRunner(new MappedFileSource(args[0])).runWith(this);
        long tMatch = System.currentTimeMillis() - tStart;
        System.out.println("total time taken: " + (tMatch) / 1000.0);
    }

    public static void main(String[] args) throws Exception {
        args = new String[1];
        args[0] = "C:\\Users\\Administrator\\Desktop\\6056841517.dem";

        new MyTest().run(args);
    }

}

There might be more bugs, I only went through 1 replay. However you can see the OrderType which throw NPE, and then deal with it. Here is part of my outputs:


entindex: 8
order_type: 11
units: 895
ability_id: 898
queue: false
sequence_number: 344
flags: 0

entiindex: CDOTAPlayer
order_type: DOTA_UNIT_ORDER_TRAIN_ABILITY
Unit: CDOTA_Unit_Hero_Tidehunter
ability_id: CDOTA_Ability_Tidehunter_AnchorSmash
0:41
============================
entindex: 2
order_type: 4
units: 1018
target_index: 120
queue: false
sequence_number: 916
flags: 0

entiindex: CDOTAPlayer
order_type: DOTA_UNIT_ORDER_ATTACK_TARGET
Unit: CDOTA_Unit_Hero_Luna
target: CDOTA_BaseNPC_Creep_Lane
0:41
============================

I still have problem with sequence_number adn flags, maybe other words I didn't see. But I guess now we're good to repeat every single movement of every player.

**Comment by spheenik** [comment]
Hint: I think the order type corresponds to `DotaCommonMessages.dotaunitorder_t`.

[click me](https://github.com/skadistats/clarity-protobuf/blob/06462f2215628f5531f06de5ab5fdb6baf192ffb/src/main/proto/common/dota_commonmessages.proto#L105-L145)

**Comment by BusyLivingDota** [comment]
Hi:

You didn't reply for days and I'm not sure you sent friend request, here is
all my friend request list which is your son's account?

Sincerely,
Haoran

Martin Schrodt ***@***.***> 于2021年7月3日周六 上午2:10写道：

**Comment by spheenik** [comment]
closing this, because I'm in a cleaning up mood. Feel free to reopen if more questions.
