### ISSUE TITLE
Offset between Match.getTick() and actual game ticks. 

### ISSUE THREAD

**Issue by TimotheeJeannin** [skadistats/clarity#35]
First, **thank you for this awesome parser, it is great !** :)

I found one minor issue. It looks like there is an offset between the ticks returned by the parser and actual game ticks. I made a few tests on three replays. Please see the results below.

**MatchId: 1174817178**

| Killer Hero | Clarity Tick | Actual game tick | Difference |
| ------------- |:-------------:| -----:| -----:|
vengefulspirit | 11944 | 11513 | 431
vengefulspirit | 16378 | 15947 | 431
vengefulspirit | 19514 | 19083 | 431
queenofpain | 21118 | 20687 | 431
queenofpain | 27684 | 27253 | 431
life_stealer | 34714 | 34284 | 431
vengefulspirit | 42618 | 42187 | 431
luna | 56775 | 56344 | 431

**MatchId: 1174817703**

| Killer Hero | Clarity Tick | Actual game tick | Difference |
| ------------- |:-------------:| -----:| -----:|
legion_commander | 16525 | 16038 | 487

**MatchId: 1174822113**

| Killer Hero | Clarity Tick | Actual game tick | Difference |
| ------------- |:-------------:| -----:| -----:|
bloodseeker | 11624 | 11126 | 498
phantom_assassin | 31786 | 31288 | 498

It looks like the offset is constant during a match but different between matches.

To navigate between game ticks I use the `demo_gototick` command.

From the clarity source I can read `tick = ((CNETMsg_Tick) subMessage).getTick();`. It looks like clarity just uses the ticks found in protobuff messages. 

Do you have any idea where this offset is coming from ?
I don't really need this fixed but it would be great to be able to understand what is happening here. :)

Tim

**Comment by TimotheeJeannin** [comment]
After further investigations, it appears that the very first tick returned by clarity is equal to the offset I saw on the three tested replays.

**Comment by spheenik** [comment]
Hi,

thanks for the praise :)

This is gonna be technical, but I can't explain it otherwise...

There's actually 2 types of tick offsets in the replay file:

- a zero based tick (replay time), called peekTick below
- a tick value determined from CNETMsg_Tick, called tick below

The value you see in match is the second one. It is a strange value, since in the replay header it is a value X, but then, when the replay starts it rewinds to a smaller, non null value Y, which is smaller than X. 
There was a time when I was thinking that it still had informational merit - for example, given a single replay time tick, there are often several messages, and sometimes the CNETMsg_Tick is not the first one - as if the packets belong to the last tick, but could not have been sent or written back then, so they arrive now.

for example (Match ID 163454120, but it's the same thing with all replays):

Replay Header:
id: 0, peekTick: 0, tick: 0, full: false, border: NONE, messageType: CDemoFileHeader
id: 1, peekTick: 0, tick: 0, full: false, border: NONE, messageType: CSVCMsg_ServerInfo
id: 2, peekTick: 0, tick: 2917, full: false, border: NET, messageType: CNETMsg_Tick
...
id: 746, peekTick: 0, tick: 2917, full: false, border: NONE, messageType: CSVCMsg_SetView
id: 747, peekTick: 0, tick: 2917, full: false, border: NONE, messageType: CNETMsg_SignonState
id: 748, peekTick: 0, tick: 2917, full: false, border: NONE, messageType: CDemoSyncTick

The CDemoSyncTick marks the end of the header.
It then continues with:

id: 749, peekTick: 0, tick: 356, full: false, border: NET, messageType: CNETMsg_Tick
id: 750, peekTick: 0, tick: 356, full: false, border: NONE, messageType: CSVCMsg_PacketEntities

So while for peekTick it's still at tick 0, it actually jumped "back in time" for tick, and from now on, the offset between the two remains constant (356 in this case, different for all replays, and most certainly what your tests yielded).

I was under the impression that match.getReplayTime() would return the time based on peekTick, but it doesn't, which is a bug.

I'm going to repair that soon, and then match.getTick(), and match.getReplayTime() will be based on the peekTick.

**Comment by TimotheeJeannin** [comment]
Hi @spheenik,

Thank you for all those explanations. I now understand a lot better where does the offset comes from. 

Thank you again for this awesome parser ! :)

Tim

**Comment by spheenik** [comment]
fixed in 2.0-dev branch.
