### ISSUE TITLE
RuntimeException: oops. no provider found for required usage point interface...

### ISSUE THREAD

**Issue by epicbo** [skadistats/clarity#43]
First of all I wasn't sure if this is the right place to put it, but I couldn't find anywhere else to ask for help.

Second, it is very possible that this isn't a bug. It could just be me doing something wrong. I admit I have pretty much no experience with Maven, so that could be the reason why this is happening.

Anyway I downloaded both Clarity and Clarity-examples, and imported the projects into eclipse. There I tried to run several examples, most of them gave the error in the title. The only one working (I did not try them all yet) is examples.info. For example, the example.combatlog gives the following error:

http://i.gyazo.com/cf9e4097a48a4337106aaa4a0fbda4e2.png

While the examples.matchend gives:

http://i.gyazo.com/a70b6beb0b40464d2df8458cda409d7a.png

The error is similar for every example.

**Comment by spheenik** [comment]
Hmm, this looks like your eclipse did not pick up the annotation processor (it's named classindex, it's on Github too).

Are you building via the m2e (Maven integration in eclipse)?

If so, this might help: https://immutables.github.io/apt.html#eclipse

**Comment by epicbo** [comment]
Thanks for the super quick reply!

I tried deleting everything and downloading it again. I have no idea what I did different this time but it's working now!

**Comment by spheenik** [comment]
You're welcome, and do not hesitate to ask if you have more questions :)

**Comment by arinik9** [comment]
Hello!

I have some problem/difficulties to run your examples on Eclipse with Maven Integration. Actually, I have pretty much no experience with Maven, so that could be the reason why this is happening.
I got same problem as @epicbo did :  "oops. no provider found for required usage point interface ..."

Anyway I downloaded both Clarity and Clarity-examples, and imported the projects into eclipse (2 separate projects). There I tried to run several examples (for example => combat log), most of them gave the error in the title. Before running some examples, I added "clarity" project in "clarity-examples" project's build path in order to get Model and the other source classes. And I provided my own replay file with args[] in Eclipse.

What sould I do for running the examples? Actually, I dont understand why you need 2 separete projects. Why not just 1? Maybe my problem come from that reason? Thanks in advance.

**Comment by arinik9** [comment]
I think I can't build the maven command: "mvn -P combatlog package" where package is "combotlog skadistats.clarity.examples.combatlog". Maybe my package variable is wrong

Because I dont have any jar file under target directory.

Is not there any simple manual ? :)

**Comment by spheenik** [comment]
You can solve this by enabling annotation processing in eclipse, 
https://immutables.github.io/apt.html#eclipse
, and afterwards rebuilding the project.

**Comment by spheenik** [comment]
Also:

On 12/14/2015 02:21 PM, Nejat wrote:
>
> I think I can't build the maven command: "mvn -P combatlog package" 
> where package is "combotlog skadistats.clarity.examples.combatlog". 
> Maybe my package variable is wrong
>

Yes that is indeed wrong!
Do not replace anything, and just enter

`mvn -P combatlog package`

in the base directory of clarity-examples.

**Comment by frozenspider** [comment]
Thanks, it was useful for me as well, I was really confused at first.
Maybe it would make sense to add this to README file?
