### ISSUE TITLE
updating protobufs

### ISSUE THREAD

**Issue by howardc93** [skadistats/clarity#45]
How are the protobufs for clarity updated?

I notice that you have a repo called clarity-protogen:

https://github.com/spheenik/clarity-protogen

There are also make.sh and update.sh files in the same directory as the .proto files:

https://github.com/skadistats/clarity-protobuf/tree/master/src/main/proto

Do both of these generate the Java classes found here:

https://github.com/skadistats/clarity-protobuf/tree/master/src/main/java/skadistats/clarity/wire/proto

Is the first simply a pure-Java implementation, while the second uses the protoc binary?

**Comment by spheenik** [comment]
The protobufs are updated by releasing a new version of https://github.com/skadistats/clarity-protobuf

I factored the protobufs out into a separate package so they can be used by clarity 1 and 2 simultaneously.

The source files in there (.proto) are basically hand crafted since clarity 1.0, since they contain valves additions since then, but keep the removals (to be able to parse old replays).

The clarity-protogen projects is a half-ready tool that (when finished) should do that merging process automatically. The idea is to check out the git-Repo from steam kit, and analyze .proto-Definitions over time, keeping additions but skipping removals, as well as to produce a subset of Valve's definitions that leaves out all message definitions never found in replays. 

So to update the protobufs, put them into https://github.com/skadistats/clarity-protobuf/tree/master/src/main/proto and run protoc.

Question: Do you need new protobufs?

**Comment by howardc93** [comment]
not at the moment, but it's good to know how to update them.

I forked clarity and wrote my own script to fetch and generate protobuf classes:
https://github.com/yasp-dota/clarity

I may also play around with source 2 parsing.

**Comment by howardc93** [comment]
Doesn't the protobuf format allow backwards compatibility with previous data?  The latest protobuf should work with old replays without needing to filter out the removals.

**Comment by spheenik** [comment]
Exceptions prove the rule….

You might be right, but I saw some changes during that time that made it look like a good idea to preserve the removals.
