### ISSUE TITLE
Issues with OnEntityXXXXXed

### ISSUE THREAD

**Issue by 1zb** [skadistats/clarity#64]
Hi,

1. What's the difference between OnEntityCreated and OnEntityEntered?
2. Can we use OnEntityDeleted to detect the death of wards and creeps? The results seem to go so wrong.

Thanks for your time.

**Comment by spheenik** [comment]
1) OnEntityCreated is emitted when the entity is first created in the entity table
2) Each entity has an attached flag which indicates whether it receives updates from the server at the moment. For live replay data, an entity the flag is deleted (for your client)  when the entity leaves your field of vision, and set when it enters the field of vision. Since complete replays are not from the view of a client, but from the server, all entities remain in the field of view all the time. So these cannot be used to detect dying wards... (since the entity is still there)

To check for deaths, use OnEntityUpdated, and check whether the lifestate of the entity changed.

**Comment by spheenik** [comment]
@1zb, @howardchung Quick heads up: Since this is such a nice example of how one could extend clarity, I implemented a new provider + example for just this:

https://github.com/skadistats/clarity-examples/tree/master/src/main/java/skadistats/clarity/examples/lifestate

SpawnsAndDeaths.java is the processor that provides the events, and Main.java is an example of how to use them.

I don't know yet if I should move the provider over to the library, or leave as an example...

**Comment by howardchung** [comment]
What's the difference between Died and Dying?

**Comment by spheenik** [comment]
Dying: Dropped below 0 health and the death animation has started
Died: Completely dead

I think when you get killed with an aegis, you will reach state dying, 
but not state dead.
Same with Wraith King's ulti.
Didn't check though.

**Comment by 1zb** [comment]
I tested dying and died on CDOTA_Unit_Hero_SkeletonKing. (MatchID 1886916978)

tick, time, state, m_iDeaths, replicate model
> 011881, 02:21, dying, death = 1, replicate = 16777215
> 011971, 02:24, died,  death = 1, replicate = 16777215

> 016330, 04:49, dying, death = 2, replicate = 16777215
> 016422, 04:52, died,  death = 2, replicate = 16777215

> 019198, 06:25, dying, death = 3, replicate = 16777215
> 019288, 06:28, died,  death = 3, replicate = 16777215

> 031844, 13:26, dying, death = 3, replicate = 16777215 (ultimate)

> 032328, 13:42, dying, death = 4, replicate = 16777215
> 032418, 13:45, died,  death = 4, replicate = 16777215

> 046372, 21:30, dying, death = 4, replicate = 16777215 (ultimate)

> 046972, 21:50, dying, death = 4, replicate = 16777215
> 047064, 21:53, died,  death = 4, replicate = 16777215  (aegis)

> 051456, 24:20, dying, death = 4, replicate = 16777215 (ultimate)

> 055212, 26:25, dying, death = 4, replicate = 5178007 (illusion)
> 055212, 26:25, dying, death = 4, replicate = 5178007 (illusion)
> 055302, 26:28, died,  death = 4, replicate = 5178007 (illusion)
> 055302, 26:28, died,  death = 4, replicate = 5178007 (illusion)

> 057560, 27:43, dying, death = 4, replicate = 16777215 (ultimate)

> 063234, 30:52, dying, death = 4, replicate = 16777215 (ultimate)

> 063434, 30:59, dying, death = 5, replicate = 16777215
> 063522, 31:02, died,  death = 5, replicate = 16777215 

> 072736, 36:10, dying, death = 5, replicate = 16777215 (ultimate)

Dying -- killed with WK's Ult (tick = 031844, game time = 13:26)
Died  --  killed with an Aegis (tick = 047064, game time = 21:53)

Between Dying and Died, there is a 2 sec or 3 sec gap.

**Comment by spheenik** [comment]
so this means when WK ulti triggers, there is no OnEntityDied, while dying on aegis triggers it?

**Comment by 1zb** [comment]
Yeah. I believe so.
