### ISSUE TITLE
CS:GO version

### ISSUE THREAD

**Issue by SeanyC** [skadistats/clarity#75]
Would it be possible to leverage some of this codebase for use with CS:GO demos? Or would it be better to start from scratch?

**Comment by spheenik** [comment]
Basically yes.

I have this request in the drawer since December, but have not gotten 
around to implementing it yet.

 From what I hear, "all" you had to do is add CS:GO protobufs to the 
clarity-protobuf project, and add a new EngineType for CS:GO. Do you 
have access to CS:GO demos?

Am 17.02.2016 um 00:27 schrieb Sean Conlin:

**Comment by spheenik** [comment]
I had a look and started implementing. It's more work than I thought, so no eta :)

**Comment by SeanyC** [comment]
very cool. let me know if you need anything. I have access to demos, but you should be able to get a ton from hltv.org.

For Example:
GOTV demos: http://www.hltv.org/?pageid=28
POV demos: http://www.hltv.org/?pageid=198

**Comment by spheenik** [comment]
I know it's been two years, but as of today, clarity supports CSGO replays. Cheers!
