### ISSUE TITLE
Mechanics of replay rendering and demo file info

### ISSUE THREAD

**Issue by mintwzy** [skadistats/clarity#94]
I am thinking how the replay file and Dota 2 client are working together to render the game. The following are some of my questions and assumptions.

## Question 1 (neutral stacking)
When we click on a replay tick, the state of current world in shown. There may be neutral stacking. How is it generated?

### Assumption 1
The state of current tick is calculated from the first tick. Tthe creeps, neutrals, towers have their own reaction mechanism. When they are attacked, they will act in the predefined way. The neutral stacking, pulling, creeps attacking are working in this way.

### Assumption 2
We have stacking info stored in the demo file, so the stacking state at a neutral point is restored for a particular tick.

## Question 2 (creep location and health)
Similar to Q1. At a particular tick, how are the creep location and health generated?

### Assumption 1
The mouse click, keyboard press, damage info are stored in the demo file, and the state of current world is generated based on the mechanism described in Assumption 1.

## General question
How do I know what info are stored in the demo file and what info are generated by the Dota 2 client? Go through all the `proto` files? 

Does anyone have any ideas on this? Thanks a lot.

**Comment by spheenik** [comment]
Q1: Both assumptions do not hold. The replay does only contain the state of the world at every tick. Every 2 minutes there is a full packet with the complete state, and differential updates in between. When a minute mark passes in the game, the server spawns entities, which will be reflected in the world state. When playing back, it'll just display the world state, and not compute anything.

Q2: There are no actions whatsoever in the replay file. No state is generated when playing back. You only see the results of actions done (changes in health for example).

Starcraft for example uses a system where they store player actions in the replay. This has the disadvantage that a later client cannot play back an earlier replay, since things change in patches, for example the damage amount a nuke does. So to be able to play back a replay from an old patch with the current client, there must not be a single computation done from an action while playing back

**Comment by spheenik** [comment]
1) the replay contains an entity for every building, hero, creep, neutral. That entity contains life state, health, position and so on. There might be an entity for a neutral-camp, but I am not sure.
2) yes. There's several IDs for an entity: First is it's index in the entity table, the other is a so called handle.

You can get to entity data, by using the Entities-processor, for example:

```java
ctx.getProcessor(Entities.class).getByHandle(theHandle)
ctx.getProcessor(Entities.class).getByIndex(theIndex)
ctx.getProcessor(Entities.class).getAllByPredicate(yourPredicate)
```

To enable entity processing, you have to annotate your processor with `@UsesEntities`.

I recommend using [clarity analyzer](https://github.com/spheenik/clarity-analyzer) to see what data there is.

**Comment by mintwzy** [comment]
Thanks for the recommendation, I will try it now! 👍
