### ISSUE TITLE
calculate KDA

### ISSUE THREAD

**Issue by Raikiree** [skadistats/clarity#98]
Hi, I noticed that the KDA value of a hero is not stored under those properties, am I right? If so, does it mean we have to parse the combatlog to calculate the kills and deaths? Also for the assists, under what condition could a hero be considered performed an assist?
Thanks!

**Comment by spheenik** [comment]
I am not sure what you mean by "those properties".

To get the KDA you better not use the combat log, but entities, since only there you have a reliable assist count. 

See the [matchend example](https://github.com/skadistats/clarity-examples/blob/master/src/main/java/skadistats/clarity/examples/matchend/Main.java) on how to get to the data.

**Comment by Raikiree** [comment]
thank you!
